{% set name = "databases" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databases-{{ version }}.tar.gz
  sha256: 6544d82e9926f233d694ec29cd018403444c7fb6e863af881a8304d1ff5cfb90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sqlalchemy >=1.4.42,<1.5

test:
  imports:
    - databases
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/encode/databases
  summary: Async database support for Python.
  license: BSD-3-Clause
  license_file: LICENSE.md
  description: |
    Databases gives you simple asyncio support for a range of databases.

    It allows you to make queries using the powerful SQLAlchemy Core expression 
    language, and provides support for PostgreSQL, MySQL, and SQLite.

extra:
  recipe-maintainers:
    - carlodri
    - thewchan
