{% set name = "databases" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 530d5f489338bf34886cad0fb6f1584922cb25ce9684afec63c37f00e8d6725d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sqlalchemy
    - aiocontextvars  # [py<37]
    - asyncpg
    - aiomysql
    - aiosqlite

test:
  imports:
    - databases

about:
  home: https://github.com/encode/databases/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Async database support for Python. 🗄
  description: |
    Databases gives you simple asyncio support for a range of databases.

    It allows you to make queries using the powerful SQLAlchemy Core expression 
    language, and provides support for PostgreSQL, MySQL, and SQLite.
  doc_url: https://github.com/encode/databases/
  dev_url: https://github.com/encode/databases/

extra:
  recipe-maintainers:
    - carlodri
